### ISSUE TITLE
Please do not direct machinekit users to linuxcnc mailing lists

### ISSUE THREAD

**Issue by jepler** [machinekit/machinekit#1017]
Hi.  I noticed today that the machinekit google group directs users to the linuxcnc mailing lists:

> Topics which relate to both LinuxCNC and Machinekit right now, like usage and configuration will likely find a better audience at emc-developers and emc-users.

If this is text that you can change/update, I think it would benefit machinekit users to do so.

Thanks for your time.

**Comment by mhaberler** [comment]
done.

**Comment by jepler** [comment]
@mhaberler thank you
