### ISSUE TITLE
hal.kernel_version missing in non RTAPI versions

### ISSUE THREAD

**Issue by andypugh** [machinekit/machinekit#102]
The hal.kernel_version tag is only added if RTAI is defined. 
This means that stepconf test-axis (and probably the same in pncconf) doesn't work. 

problem caused at 
src/hal/halmodule.cc : 1159
makes things go wrong at 
src/emc/usr_intf/stepconf/stepconf.py : 724
src/emc/usr_intf/pncconf/pncconf.py : 4304

**Comment by zultron** [comment]
@luminize, addressing your question in #60, this problem applies to userland threads.  Here's the code:

https://github.com/machinekit/machinekit/blob/master/src/hal/lib/halmodule.cc#L1167-L1169
https://github.com/machinekit/machinekit/blob/master/src/emc/usr_intf/stepconf/stepconf.py#L807-L808
https://github.com/machinekit/machinekit/blob/master/src/emc/usr_intf/pncconf/pncconf.py#L4222-L4223
