### ISSUE TITLE
Interest for Machinekit meeting in the states?

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#1059]
It is almost a year since the last Machinekit meeting at the Tormach facility in Wisconsin. Therefore, I would like to gauge some interest for another Machinekit meeting in the states this Fall or Spring 2017.

Is anyone else interested? Are there any location or time preferences?

**Comment by prcdslnc13** [comment]
Would love to see it happen. I missed last year and would like to make it this year.

**Comment by pmcstone** [comment]
Tormach make it happen :+1:

**Comment by machinekoder** [comment]
Does not look like there is a lot of discussion going on here.

Early February would be the optimal time.

**Comment by machinekoder** [comment]
I created a doodle poll: 
http://doodle.com/poll/32kkc5pnkyfuxpun

**Comment by machinekoder** [comment]
I updated the poll for April, since February and March turned out to be too busy.

**Comment by luminize** [comment]
This meeting has happened.
