### ISSUE TITLE
`configure.ac` doesn't check for `g++`

### ISSUE THREAD

**Issue by zultron** [machinekit/machinekit#1064]
If `g++` isn't installed, `./configure` fails with `configure: error: boost::python is required to build LinuxCNC`.

**Comment by zultron** [comment]
This is also a problem when cross-compiling because the `g++` matching the host isn't found.

**Comment by zultron** [comment]
Actually, it looks like the needed `AC_PROG_CXX` is there, but it needs to be earlier in the file.  I'll put in a PR later.

**Comment by ArcEye** [comment]
I have seen messages in the past from people who have had this error and were confounded, 
because they had all the boost libs installed.

Never had it myself, but the first thing I do on a new partition is install a full build environment.

Good spot.
