### ISSUE TITLE
option singleton causes halcmd lock up with icomps

### ISSUE THREAD

**Issue by ArcEye** [machinekit/machinekit#1094]
Ref  #1093

I am not going mad, there IS a problem with the `thc` and `thcud` components.

If you do a fresh clone and build then
`DEBUG=5 realtime restart`
`halcmd loadrt thc`

I get halcmd locking with high single CPU activity until I kill the process

`/var/log/linuxcnc.log` just shows that thc was loaded from thc.so, no error at all

I was rather a loss as to what could be causing it either locally or globally

By process of elimination, discovered that commenting out
`option singleton yes`
cures it

This only occurs in thc and thcud and is an anachronism from the .comp file, since singleton does not really have a useful meaning in relation to instantiated components.
(If you just want one, don't create more than one)

There is a kernel module marker put in components that use that option and halcmd_commands.c
has code that checks for existing instances if it is found.
That is where I need to look next.

**Comment by zhivko** [comment]
Its funny how it doesnt happen on bbb.
So commenting out singleton fixes it?

**Comment by ArcEye** [comment]
Yes, albeit I have now deprecated the whole `option singleton` so it definitely won't happen again.
