### ISSUE TITLE
lincurve icomp erroneous output

### ISSUE THREAD

**Issue by propcoder** [machinekit/machinekit#1127]
lincurve and lincurvev2 icomponents return enormous values, totally out of scale, sometimes negative when only positive input numbers exist. (master branch, latest version)

The difference from LinuxCNC lincurve.comp is in line 60.
Shouldn't it be:
sf(out_, gf(y_val(i)) + f * (gf(y_val(i+1)) - gf(y_val(i)) )) ;
instead of:
sf(out_, ( gf(y_val(i)) + f) * (gf(y_val(i+1)) - gf(y_val(i)) )) ;
?

**Comment by ArcEye** [comment]
I think @machinekoder fixed it a long while back, but the code has got reverted in the recent merge.

I will look at it in a while.

Thanks for the report.

**Comment by luminize** [comment]
I think the issues are #818 #784

**Comment by ArcEye** [comment]
You are right and it was me that fixed it, @machinekoder reported it.
All blurs into one after a while. :smile:

I will sort it soon.

**Comment by ArcEye** [comment]
PR #1128 hopefully fixes back to how it was.
Will take about 90 minutes from when it is merged for all the packages to appear, armhf ones still not building right now.

**Comment by ArcEye** [comment]
0.1.1486851828-1mk.travis.master.gitcbd2dfd3
is the relevant serial for the build with lincurve corrected.

Unfortunately wheezy-armhf builds not working yet.
