### ISSUE TITLE
Removing Webtalk from build?

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#1129]
Webtalk adds a dependency to libwebsocket which is complicated to resolve on many systems since a special version of the library is required and Websockets are a moving target right now. However, Webtalk is not used in any project I know of.

I suggest removing Webtalk from the Machinekit main repository or deactivate it in the default build configuration. Even better would be to replace it with a Node.js based solution like this one: https://github.com/machinekoder/Webvcp

**Comment by ArcEye** [comment]
I am all for simplifying builds and removing dependencies.

I would suggest that a configure option of  `--with-option-webtalk` would be the easiest way to remove the dependency but retain the code to use it if required.

If webtalk is not in use, replacing it with another solution does not seem a profitable use of time.

**Comment by ArcEye** [comment]
It can be done quite simply as at
https://github.com/ArcEye/machinekit/commit/5d8a7de21bce4e1459b1c2f5984722ca55d9a446

Tested and `./configure --enable-webtalk` will build, otherwise is ignored.

(ignore the other headers the commit removes, I based it on the wrong branch initially)

**Comment by machinekoder** [comment]
Excellent! This makes the build a lot easier, especially for new users.

**Comment by ArcEye** [comment]
OK based it upon the proper branch now
https://github.com/ArcEye/machinekit/commit/c357fe1e79a453caaf1a68482d295119c113de75

I can do a PR if you want.
Depends how sure you are that no-one uses it?

**Comment by ArcEye** [comment]
Email sent out to the list as a poll.

If no responses or only from those using RIPs, this could be dropped from Travis builds and remain as an option for local builds.

**Comment by ArcEye** [comment]
Only response has been one person who says he doesn't use it but would like it left in just in case he ever changes his mind (to paraphrase) :stuck_out_tongue_closed_eyes: 

PR #1149 refers
