### ISSUE TITLE
Watchdog interface has changed

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#1142]
The interface of the watchdog component has changed due to port to instcomp:
```bash
$ halcmd loadrt watchdog num_inputs=3
<commandline>:0: 
Invalid argument 'num_inputs=3' to instantiated component
NB. Use of personality or cfg is deprecated
```

The new parameter is called `pincount`. Should we really break backward compatibility?

**Comment by machinekoder** [comment]
We should also change:
https://github.com/machinekit/machinekit/blob/master/lib/python/fdm/config/base.py#L34
accordingly

**Comment by ArcEye** [comment]
> Should we really break backward compatibility?

There is no backward compatibility for all the multi-various module args that had grown up in legacy rt modules, 
halcmd does not support loadrt args for instcomps, other than `count=` and `names=`.

In that respect it is fully compatible with every other instantiated component, in that pincount controls the number of pins within an instance.

I had not realised the python libs used it, I will do a PR substituting `newinst` for `loadrt` in that code
