### ISSUE TITLE
Switch ARM configurations to velocity-mode

### ISSUE THREAD

**Issue by cdsteinkuehler** [machinekit/machinekit#131]
Switch to velocity-mode for PRU step/dir generation with HAL based PID loop to allow dead-band adjustment and eliminate "hunting" on the direction output.

**Comment by machinekoder** [comment]
In the meantime, PRU pin hunting has been fixed. A problem in some cases is still the joint following errors which can be caused by some types of GCode. Not sure if this is related to PRU or the BBB as a platform though. I experience this problem more frequently with RT_PREEMPT.
