### ISSUE TITLE
Machintkit on i.MX6 board

### ISSUE THREAD

**Issue by Savoyyang** [machinekit/machinekit#1322]
hey , I know LinuxCNC(Machinekit) can transplant to BeagleBoneBlack(Debian)和Raspberry Pi3(Debian)，Now I want to transplant on i.MX6 board，but can't find more information on internet. I know this is possible, but there is no more information, can you provide some information, thank you very much.

**Comment by ArcEye** [comment]
Please use the forum, the Issues is not the place for requests for info
https://groups.google.com/forum/#!forum/machinekit
