### ISSUE TITLE
BB-blue BB-enhanced : machinekit and stepper compatibility 

### ISSUE THREAD

**Issue by alkabal** [machinekit/machinekit#1353]
Hi

I have too many problem with industrial version from element14 so i check for other choice.

It is possible with Beaglebone-blue to control motor stepper driver like leadshine dm556 ?

Also for this use, machinekit can work fine with this board ?

Is Beaglebone enhanced work fine with machinekit and standard cape ?

Best regards.

**Comment by ArcEye** [comment]
This is for issues with Machinekit not questions about hardware.
You have already posted in the correct place, on the forum.
