### ISSUE TITLE
referencing LCNC issues in commits from a machinekit fork will add wrong relations

### ISSUE THREAD

**Issue by luminize** [machinekit/machinekit#1355]
referencing linuxcnc issues in commits (hashtag + number) on a machinekit fork links back to machinekit organisation repos issues while these numbers definitely don't match.
for example like here:
https://github.com/machinekit/machinekit/issues/134#ref-commit-c00bd8b

**Comment by ArcEye** [comment]
I think this is a Github thing.
Any reference is assumed to be one to THAT repo.
You cannot get a proper reference to a commit or issue in another repo in the same organisation, unless you include the full URL and that sometimes does not work.

**Comment by luminize** [comment]
Ok, well it's really annoying when you read thru an issue and see all nonsense references. I'll look if we can turn the referencing from forked repo's off. Then we can decide if we want that.

**Comment by cdsteinkuehler** [comment]
On 2/11/2018 11:25 AM, Bas de Bruijn wrote:
> Ok, well it's really annoying when you read thru an issue and see
> all nonsense references. I'll look if we can turn the referencing
> from forked repo's off. Then we can decide if we want that.

I think it works properly if you use the full user/repo#issue format
(or user/repo@commit) ie:

linuxcnc/linxucnc#134

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by ArcEye** [comment]
@luminize is there anything further on this or can it be closed?
