### ISSUE TITLE
Build is littered with compiler warnings

### ISSUE THREAD

**Issue by zultron** [machinekit/machinekit#1368]
The build is littered with compiler warnings.  When compiling my updates, this makes it really hard to tell if I've introduced a new warning.  #327 had them all fixed a couple of years back, but that was never merged, and it's unclear how many of those patches still address outstanding warnings, or how many would even apply.

**Comment by ArcEye** [comment]
Your original fixes were against gcc 4.9.2

I am now using gcc 7.3.0-14 and it is getting super picky, g++ even more so.

When building against some machinekit headers with Qt5, I am now having to add 
`-Wno-ignored-qualifiers` to the `QMAKE_CXXFLAGS` to get around the number of functions which declare with `static char*` but actually return `char*` and similar.

There is a set of inline macros which produce dozens of these warnings / errors (depending upon how strict your build).  They defied easy amendment and I just worked around them as above.

Certainly could do with cleaning up.

**Comment by zultron** [comment]
Thanks for the tips.  I'm still on gcc 5 in stretch, but I'll fix the ones I can.
