### ISSUE TITLE
GIPO DRIVER NOT WORKING

### ISSUE THREAD

**Issue by tjmarch** [machinekit/machinekit#1381]
Having trouble getting gipo's to work can get all to show up as outputs but when I load comp no pins are available output or input. The following is my work sheet for what I am trying to achieve

BOB    SIGNAL     GIPO    IN or OUT       RPI PIN    BINARY

P2 =    XPUL    = GIPO2  =   OUT      =       3    =    1
P3 =    XDIR     = GIPO3  =   OUT      =       5    =    1
P4 =    YPUL    = GIPO4  =   OUT      =       7    =    1
P5 =    YDIR     = GIPO5  =   OUT      =      29   =    1
P6 =    UPUL    = GIPO6  =   OUT      =      31   =    1
P7 =    UDIR     = GIPO7  =   OUT      =      26    =    1
P8 =    VPUL    = GIP08  =   OUT       =      24    =    1
P9 =    VDIR    = GIPO9  =   OUT       =      21    =    1
P10=   ESTOP = GIPO10 =   IN         =      19    =    0
P11=X AXIS LIMIT= GIPO11 =   IN    =      23    =    0
P12=Y AXIS LIMIT= GIPO12 =   IN    =      32    =    0
P13=U AXIS LIMIT= GIPO13 =   IN    =      33    =    0
P14=    ENABLE    = GIPO14 = OUT  =       8    =    1
P15=V AXIS LIMIT= GIPO15 =   IN    =      10    =    0
P16=    BPUL        = GIPO16 =OUT    =      36    =    1
P17=  BDIR/RELAY= GIPO17 =OUT   =      11    =    1
P1 =    PWM          = GIPO18 =OUT   =      12    =    1
GND=   PC GROUND=   ~      =    ~    =       9    =    ~
PCGND= PC GROUND=   ~    =    ~   =      14    =    ~
PC5V=  PC 5 VOLT=   ~        =    ~    =       2    =    ~
PC5V=  PC 5 VOLT=   ~       =    ~     =       4    =    ~
--------------------------------------------------------------
loadrt hal_gpio dir=0x??????????????
1 means output
0 means input

you can exclude pins that you will not use

loadrt hal_gpio dir=0x???????? exclude=0x???????
1 means don't use this pin
0 means use this pin

or you can directly write binary numbers in loading hal_gpio comp
------------------------------------------------------------------------

#rpi2_gpios[] = {2, 3, 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27 };
#rpi2_pins[] =  {3, 5, 7, 29, 31, 26, 24, 21, 19, 23, 32, 33,  8, 10, 36, 11, 12, 35, 38, 40, 15, 16, 18, 22, 37, 13 };

     dir=0x      1  1  1   1   1   1   1   1   0   0   0   0   1   0   1   1   1   0   0   0   0   0   0   0   0   0                 
 exclude=        0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   1   1   1   1   1   1   1   1                                                   
----------------------------------------------------------------
#commandline
echo 'ibase=2;A;11111111000010111000000000' | bc
10
66858496

echo 'ibase=2;A;00000000000000000111111111' | bc
10
511
------------------------------------------------------------------
#For my BOB
loadrt hal_gpio dir=0x11111111000010111000000000 exclude=0x00000000000000000111111111
or
loadrt hal_gpio dir=66858496 exclude=511

------------------------------------------------------------------

To get pins to show as all outputs I use:
must comment out all net input lines with hash tag in standard pinout file
loadrt hal_gipo

I am running Raspbian Jessie this is a new install of OS the output for dmesg is as follows

pi@raspberrypi:~ $ machinekit
MACHINEKIT - 0.1
Machine configuration directory is '/home/pi/machinekit/configs/my-foam'
Machine configuration file is 'my-foam.ini'
Starting Machinekit...
rtapi_msgd command:  /usr/libexec/linuxcnc/rtapi_msgd --instance=0 --rtmsglevel=1 --usrmsglevel=1 --halsize=524288
rtapi_app command:  /usr/libexec/linuxcnc/rtapi_app_rt-preempt --instance=0
io started
halcmd loadusr io started
standard_pinout.hal:25: Pin 'hal_gpio.pin-03-out' does not exist
Shutting down and cleaning up Machinekit...
Cleanup done
Machinekit terminated with an error.  You can find more information in the log:
    /home/pi/linuxcnc_debug.txt
and
    /home/pi/linuxcnc_print.txt
as well as in the output of the shell command 'dmesg' and in the terminal
pi@raspberrypi:~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.43-rt31-rc1-v7+ (pi@raspberrypi) (gcc version 4.9.2 (Raspbian 4.9.2-10+deb8u1)) #1 SMP PREEMPT RT Mon Jun 11 01:27:42 EDT 2018
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Rev 1.2
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 8 MiB at 0x3a800000
[    0.000000] On node 0 totalpages: 241664
[    0.000000] free_area_init_node: node 0, pgdat 80c898c0, node_mem_map b9faa000
[    0.000000]   Normal zone: 2124 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 241664 pages, LIFO batch:31
[    0.000000] percpu: Embedded 17 pages/cpu @b9f53000 s40960 r8192 d20480 u69632
[    0.000000] pcpu-alloc: s40960 r8192 d20480 u69632 alloc=17*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 239540
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1440 bcm2708_fb.fbheight=900 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=1228887d-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 935632K/966656K available (7168K kernel code, 577K rwdata, 2092K rodata, 1024K init, 733K bss, 22832K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
    vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
    lowmem  : 0x80000000 - 0xbb000000   ( 944 MB)
    modules : 0x7f000000 - 0x80000000   (  16 MB)
      .text : 0x80008000 - 0x80800000   (8160 kB)
      .init : 0x80b00000 - 0x80c00000   (1024 kB)
      .data : 0x80c00000 - 0x80c90500   ( 578 kB)
       .bss : 0x80c97fdc - 0x80d4f72c   ( 734 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 25255 entries in 75 pages
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000]     No expedited grace period (rcu_normal_after_boot).
[    0.000000]     Tasks RCU enabled.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000010] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000020] Switching to timer-based delay loop, resolution 52ns
[    0.000311] Console: colour dummy device 80x30
[    0.001316] console [tty1] enabled
[    0.001340] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.001353] pid_max: default: 32768 minimum: 301
[    0.001717] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001735] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002799] Disabling memory control group subsystem
[    0.002902] CPU: Testing write buffer coherency: ok
[    0.003525] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.040171] Setting up static identity map for 0x100000 - 0x10003c
[    0.080147] Hierarchical SRCU implementation.
[    0.160306] smp: Bringing up secondary CPUs ...
[    0.260988] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.361064] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.461230] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.461396] smp: Brought up 1 node, 4 CPUs
[    0.461509] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.461542] CPU: All CPU(s) started in HYP mode.
[    0.461569] CPU: Virtualization extensions available.
[    0.462858] devtmpfs: initialized
[    0.487201] random: get_random_u32 called from bucket_table_alloc+0x130/0x288 with crng_init=0
[    0.487948] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.488367] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.488431] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.489153] pinctrl core: initialized pinctrl subsystem
[    0.490674] NET: Registered protocol family 16
[    0.495434] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.504512] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.504559] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.504806] Serial: AMBA PL011 UART driver
[    0.507512] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.508243] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.566770] bcm2835-dma 3f007000.dma: DMA legacy API manager at bb813000, dmachans=0x1
[    0.569244] SCSI subsystem initialized
[    0.569651] usbcore: registered new interface driver usbfs
[    0.569775] usbcore: registered new interface driver hub
[    0.569959] usbcore: registered new device driver usb
[    0.571323] raspberrypi-firmware soc:firmware: Attached to firmware from 2017-07-03 14:16
[    0.573328] clocksource: Switched to clocksource arch_sys_counter
[    0.581565] raspberrypi-firmware soc:firmware: Get Throttled mailbox call failed
[    0.722833] VFS: Disk quotas dquot_6.6.0
[    0.722987] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.723521] FS-Cache: Loaded
[    0.723840] CacheFiles: Loaded
[    0.739731] NET: Registered protocol family 2
[    0.740994] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.741174] TCP bind hash table entries: 8192 (order: 5, 229376 bytes)
[    0.741789] TCP: Hash tables configured (established 8192 bind 8192)
[    0.742047] UDP hash table entries: 512 (order: 3, 32768 bytes)
[    0.742189] UDP-Lite hash table entries: 512 (order: 3, 32768 bytes)
[    0.742785] NET: Registered protocol family 1
[    0.743699] RPC: Registered named UNIX socket transport module.
[    0.743734] RPC: Registered udp transport module.
[    0.743764] RPC: Registered tcp transport module.
[    0.743792] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.745791] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.752538] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.768201] FS-Cache: Netfs 'nfs' registered for caching
[    0.769547] NFS: Registering the id_resolver key type
[    0.769628] Key type id_resolver registered
[    0.769658] Key type id_legacy registered
[    0.769707] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.773017] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.773244] io scheduler noop registered
[    0.773276] io scheduler deadline registered (default)
[    0.773938] io scheduler cfq registered
[    0.773971] io scheduler mq-deadline registered
[    0.774002] io scheduler kyber registered
[    0.779207] BCM2708FB: allocated DMA memory fa910000
[    0.779410] BCM2708FB: allocated DMA channel 0 @ bb813000
[    0.816158] Console: switching to colour frame buffer device 180x56
[    0.839582] bcm2835-rng 3f104000.rng: hwrng registered
[    0.839949] vc-mem: phys_addr:0x00000000 mem_base=0x3dc00000 mem_size:0x3f000000(1008 MiB)
[    0.840994] vc-sm: Videocore shared memory driver
[    0.841624] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.861138] brd: module loaded
[    0.881424] loop: module loaded
[    0.881561] Loading iSCSI transport class v2.0-870.
[    0.882687] libphy: Fixed MDIO Bus: probed
[    0.882970] usbcore: registered new interface driver lan78xx
[    0.883238] usbcore: registered new interface driver smsc95xx
[    0.883555] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.111976] Core Release: 2.80a
[    1.112088] Setting default values for core params
[    1.112264] Finished setting default values for core params
[    1.312938] Using Buffer DMA mode
[    1.313052] Periodic Transfer Interrupt Enhancement - disabled
[    1.313227] Multiprocessor Interrupt Enhancement - disabled
[    1.313441] OTG VER PARAM: 0, OTG VER FLAG: 0
[    1.313582] Dedicated Tx FIFOs mode
[    1.314362] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0xba904000 dma = 0xfa904000 len=9024
[    1.314665] FIQ FSM acceleration enabled for :
Non-periodic Split Transactions
Periodic Split Transactions
High-Speed Isochronous Endpoints
Interrupt/Control Split Transaction hack enabled
[    1.344510] dwc_otg: Microframe scheduler enabled
[    1.344574] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x80602ba8
[    1.344581] WARN::hcd_init_fiq:460: FIQ ASM at 0x80602f10 length 36
[    1.344589] WARN::hcd_init_fiq:486: MPHI regs_base at 0xbb87e000
[    1.344652] dwc_otg 3f980000.usb: DWC OTG Controller
[    1.368086] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    1.374178] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    1.380145] Init: Port Power? op_state=1
[    1.386119] Init: Power Port (0)
[    1.392221] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    1.398148] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.404034] usb usb1: Product: DWC OTG Controller
[    1.409802] usb usb1: Manufacturer: Linux 4.14.43-rt31-rc1-v7+ dwc_otg_hcd
[    1.415694] usb usb1: SerialNumber: 3f980000.usb
[    1.422588] hub 1-0:1.0: USB hub found
[    1.428554] hub 1-0:1.0: 1 port detected
[    1.435276] dwc_otg: FIQ enabled
[    1.435284] dwc_otg: NAK holdoff enabled
[    1.435290] dwc_otg: FIQ split-transaction FSM enabled
[    1.435306] Module dwc_common_port init
[    1.435643] usbcore: registered new interface driver usb-storage
[    1.441748] mousedev: PS/2 mouse device common for all mice
[    1.447866] IR NEC protocol handler initialized
[    1.453679] IR RC5(x/sz) protocol handler initialized
[    1.459429] IR RC6 protocol handler initialized
[    1.465244] IR JVC protocol handler initialized
[    1.470963] IR Sony protocol handler initialized
[    1.476779] IR SANYO protocol handler initialized
[    1.482511] IR Sharp protocol handler initialized
[    1.488279] IR MCE Keyboard/mouse protocol handler initialized
[    1.494094] IR XMP protocol handler initialized
[    1.501050] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    1.507286] bcm2835-cpufreq: min=600000 max=1200000
[    1.513624] sdhci: Secure Digital Host Controller Interface driver
[    1.519238] sdhci: Copyright(c) Pierre Ossman
[    1.525448] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    1.531744] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    1.537722] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.546815] hidraw: raw HID events driver (C) Jiri Kosina
[    1.552805] usbcore: registered new interface driver usbhid
[    1.558684] usbhid: USB HID core driver
[    1.565347] vchiq: vchiq_init_state: slot_zero = ba980000, is_master = 0
[    1.572964] [vc_sm_connected_init]: start
[    1.582743] [vc_sm_connected_init]: end - returning 0
[    1.589557] Initializing XFRM netlink socket
[    1.595408] NET: Registered protocol family 17
[    1.601348] Key type dns_resolver registered
[    1.607530] Registering SWP/SWPB emulation handler
[    1.614407] registered taskstats version 1
[    1.635538] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    1.641380] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    1.650599] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    1.656480] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    1.662474] Indeed it is in host mode hprt0 = 00021501
[    1.744600] sdhost: log_buf @ ba907000 (fa907000)
[    1.771728] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    1.780471] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.789560] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.799516] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    1.843394] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    1.856585] of_cfs_init
[    1.865452] of_cfs_init: OK
[    1.873395] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.873698] Indeed it is in host mode hprt0 = 00001101
[    1.886182] Waiting for root device PARTUUID=1228887d-02...
[    1.930246] mmc1: new high speed SDIO card at address 0001
[    1.933376] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.936198] mmc0: new high speed SDHC card at address 0002
[    1.942568] mmcblk0: mmc0:0002       30.0 GiB
[    1.944650]  mmcblk0: p1 p2
[    2.004685] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.011467] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    2.029970] devtmpfs: mounted
[    2.042096] Freeing unused kernel memory: 1024K
[    2.133967] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    2.141108] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.149619] hub 1-1:1.0: USB hub found
[    2.157054] hub 1-1:1.0: 5 ports detected
[    2.426292] systemd[1]: systemd 215 running in system mode. (+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR)
[    2.433555] systemd[1]: Detected architecture 'arm'.
[    2.483447] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    2.607786] NET: Registered protocol family 10
[    2.614059] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    2.614070] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.617159] smsc95xx v1.0.6
[    2.635832] Segment Routing with IPv6
[    2.642389] systemd[1]: Inserted module 'ipv6'
[    2.652272] systemd[1]: Set hostname to <raspberrypi>.
[    2.659041] systemd[1]: Initializing machine ID from random generator.
[    2.665792] systemd[1]: Installed transient /etc/machine-id file.
[    2.714267] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:8d:39:c3
[    2.823416] usb 1-1.2: new full-speed USB device number 4 using dwc_otg
[    2.964968] usb 1-1.2: New USB device found, idVendor=046d, idProduct=c52b
[    2.971635] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.978424] usb 1-1.2: Product: USB Receiver
[    2.985204] usb 1-1.2: Manufacturer: Logitech
[    3.214825] systemd[1]: Cannot add dependency job for unit regenerate_ssh_host_keys.service, ignoring: Unit regenerate_ssh_host_keys.service failed to load: No such file or directory.
[    3.232684] systemd[1]: Starting Forward Password Requests to Wall Directory Watch.
[    3.240580] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    3.247868] systemd[1]: Starting Remote File Systems (Pre).
[    3.659555] fuse init (API version 7.26)
[    4.150308] systemd-udevd[146]: starting version 215
[    5.969682] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[    6.150485] bcm2835_alsa bcm2835_alsa: card created with 8 channels
[    6.597568] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    6.607260] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43430-sdio.bin for chip 0x00a9a6(43430) rev 0x000001
[    6.618928] usbcore: registered new interface driver brcmfmac
[    6.849177] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Aug  7 2017 00:46:29 version 7.45.41.46
(r666254 CY) FWID 01-f8a78378
[    6.850277] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data: 9.10.41 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-08-07 00:37:47
[    7.131122] logitech-djreceiver 0003:046D:C52B.0003: hiddev96,hidraw0: USB HID v1.11 Device [Logitech USB Receiver] on usb-3f980000.usb-1.2/input2
[    7.340956] input: Logitech K400 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.2/0003:046D:C52B.0003/0003:046D:4024.0004/input/input0
[    7.345209] logitech-hidpp-device 0003:046D:4024.0004: input,hidraw1: USB HID v1.11 Keyboard [Logitech K400] on usb-3f980000.usb-1.2:1
[   14.776729] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   15.305096] systemd-journald[142]: Received request to flush runtime journal from PID 1
[   15.799351] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   15.799378] brcmfmac: power management disabled
[   16.476975] uart-pl011 3f201000.serial: no DMA platform data
[   16.895554] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   16.895976] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   16.907720] Adding 102396k swap on /var/swap.  Priority:-2 extents:4 across:241660k SSFS
[   20.884749] Bluetooth: Core ver 2.22
[   20.884862] NET: Registered protocol family 31
[   20.884871] Bluetooth: HCI device and connection manager initialized
[   20.884916] Bluetooth: HCI socket layer initialized
[   20.884946] Bluetooth: L2CAP socket layer initialized
[   20.885043] Bluetooth: SCO socket layer initialized
[   20.901474] Bluetooth: HCI UART driver ver 2.3
[   20.901490] Bluetooth: HCI UART protocol H4 registered
[   20.901498] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   20.902013] Bluetooth: HCI UART protocol Broadcom registered
[   21.072934] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   21.072945] Bluetooth: BNEP filters: protocol multicast
[   21.072968] Bluetooth: BNEP socket layer initialized
[   58.002565] logitech-hidpp-device 0003:046D:4024.0004: HID++ 2.0 device connected.
[   95.014365] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[  568.867228] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x36c08aa0
[  569.484701] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x36c08aa0
[  583.914499] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x5a431c28
[  585.564955] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x5a431c28
[  594.578986] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x25f901a0
[  596.125745] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x25f901a0
[  817.529672] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x22487d30
[  819.964433] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x22487d30
[  848.946983] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x451e28f0
[  851.740887] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x451e28f0
[  903.803840] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x299abe60
[  906.026560] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x299abe60
[  920.252102] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x4bcb59c0
[  921.355377] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x4bcb59c0
[  930.185209] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x202fd7a8
[  931.657875] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x202fd7a8
[  939.998021] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x36931ff8
[  941.126410] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x36931ff8
[  951.281444] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x40b6c7d8
[  952.855488] Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x40b6c7d8
[  962.039831] usb 1-1.2: USB disconnect, device number 4
[ 1051.948844] systemd-udevd[5111]: starting version 215
[ 1143.929921] usb 1-1.2: new full-speed USB device number 5 using dwc_otg
[ 1144.065345] usb 1-1.2: New USB device found, idVendor=046d, idProduct=c52b
[ 1144.065363] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 1144.065374] usb 1-1.2: Product: USB Receiver
[ 1144.065384] usb 1-1.2: Manufacturer: Logitech
[ 1144.085851] logitech-djreceiver 0003:046D:C52B.0007: hiddev96,hidraw0: USB HID v1.11 Device [Logitech USB Receiver] on usb-3f980000.usb-1.2/input2
[ 1144.231505] input: Logitech K400 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2/1-1.2:1.2/0003:046D:C52B.0007/0003:046D:4024.0008/input/input1
[ 1144.233650] logitech-hidpp-device 0003:046D:4024.0008: input,hidraw1: USB HID v1.11 Keyboard [Logitech K400] on usb-3f980000.usb-1.2:1
[ 1148.029956] usb 1-1.4: new high-speed USB device number 6 using dwc_otg
[ 1148.175526] usb 1-1.4: New USB device found, idVendor=6557, idProduct=4200
[ 1148.175544] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1148.175555] usb 1-1.4: Product: USB DISK 2.0
[ 1148.175565] usb 1-1.4: Manufacturer:        
[ 1148.175574] usb 1-1.4: SerialNumber: 90006AF2C71C7440
[ 1148.176903] usb-storage 1-1.4:1.0: USB Mass Storage device detected
[ 1148.179477] scsi host0: usb-storage 1-1.4:1.0
[ 1149.212110] scsi 0:0:0:0: Direct-Access              USB DISK 2.0     PMAP PQ: 0 ANSI: 6
[ 1149.234159] sd 0:0:0:0: Attached scsi generic sg0 type 0
[ 1149.298560] logitech-hidpp-device 0003:046D:4024.0008: HID++ 2.0 device connected.
[ 1151.771340] sd 0:0:0:0: [sda] 15130624 512-byte logical blocks: (7.75 GB/7.21 GiB)
[ 1151.773662] sd 0:0:0:0: [sda] Write Protect is off
[ 1151.773671] sd 0:0:0:0: [sda] Mode Sense: 23 00 00 00
[ 1151.775294] sd 0:0:0:0: [sda] No Caching mode page found
[ 1151.775302] sd 0:0:0:0: [sda] Assuming drive cache: write through
[ 1151.788998]  sda: sda1
[ 1151.798211] sd 0:0:0:0: [sda] Attached SCSI removable disk
[ 1192.443004] FAT-fs (sda1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[ 1897.809774] usb 1-1.4: USB disconnect, device number 6

I have tried this with RPI2B, RPI3B and RPI3B+ with the same results for all three.
What am I doing wrong please help.
Attached are my configs

Tim
[my-foam.zip](https://github.com/machinekit/machinekit/files/2117227/my-foam.zip)

**Comment by ArcEye** [comment]
Can you please post this to the forum, these issues are for issues with the code base not using it.

You will then reach a far wider audience, some of whom will use a Rpi, not a handfull of people who probably don't.

In addition to the info provided, you need to say what version machinekit package you installed.
