### ISSUE TITLE
hal_bb_gpio does not support PocketBeagle input pin mapping

### ISSUE THREAD

**Issue by mlampert** [machinekit/machinekit#1481]
When trying to load hal_bb_gpio on a PocketBeagle and specifying input pins in the 100 and 200 range the bb_gpio driver seems to remap them to 800 and 900 and use the BBB pin mapping. Specifically, using:

`loadrt hal_bb_gpio board=PocketBeagle input_pins=201`

Results in a `permission denied` error and linuxcnc.log has the following error:

`May 20 00:07:39 pocketbeagle rtapi:0: 1:rtapi_app:1381:user hal_bb_gpio: ERROR: invalid pin number '901'.  Valid pins are 101-136 and 201-236.`

Using the driver with only userleds or output_pins works fine though.

email thread: https://groups.google.com/forum/#!topic/machinekit/_RJ63TNH39k
@zultron

**Comment by zultron** [comment]
Thanks for figuring this out.  I submitted a PR over at #1482.
