### ISSUE TITLE
more flexible EmcPose representation

### ISSUE THREAD

**Issue by mhaberler** [machinekit/machinekit#151]
Currently the internal representation of axis positions looks like so:

```
typedef struct {
    double x, y, z;     /* this.x, etc. */
} PmCartesian;
typedef struct EmcPose {
    PmCartesian tran;
    double a, b, c;
    double u, v, w;
} EmcPose;
```

This has no provision for NULL axis values (not 0.0 but value not present).

There is no indication if the values apply to joints, or axis (pre/post kinematics, joint representation really just being a special identity kins).

Also, this is rather irregular - the benefit of the PmCartesian substructure is unclear, and the discrete-scalar representation makes iteration over axis values awkward.

While I'm not suggesting to replace this fundamental type everywhere right away, there are work items which permit experimentation with a better representaion, like preview drivers.

A future representation IMO should fulfill these requirements:
- axis are held in a sparse-array like representation
- a kinematics type indicator should be present 
- a good match on protobuf fundamental types is desirable

problem: define a more flexible representation for axis values.

**Comment by mhaberler** [comment]
it turns out ROS is using [SI](http://en.wikipedia.org/wiki/International_System_of_Units) throughout - the idea of using configurable units at the machine level as well as the UI level was a problem in the making to start with

that would be a sensible alternative to tagged quantities - it would mean all conversion happens in UI and interpreter from/to whatever is desired; from canon onwards it'd be all SI, including RT and feedback from there

**Comment by cdsteinkuehler** [comment]
+1

I like the idea of just using SI units.

I design a lot of mixed-unit circuit boards (some parts "hard" metric,
and some in inch units).  Using SI units allows correct representation
of inch with a bit of overhead (you need a few more decimal points),
but representing metric in imperial units is a royal PITA and a recipe
for many subtle bugs due to rounding issues (yes, I know from
experience using poorly designed CAD tools that tried to layer metric
support on top of an imperial unit core...gak!).

-- 
Charles Steinkuehler
charles@steinkuehler.net

**Comment by RunningLight** [comment]
As a purist, I have an affinity for tagged quantities, but as a pragmatist,
I can live with strict SI conformance. Either way, we always know what
we're dealing with when we receive data. I'll have to look at ROS in detail
to see how they deal with powers of ten, e.g., the metre is the SI unit of
length; the second, the SI unit of time. We're often, but not always,
likely to want millimetres and microseconds. [Interesting - the spell
checker on my tablet let me type metre but I had to override its
autocorrection of millimetre to millimeter.]

**Comment by RunningLight** [comment]
Ok, based on limited data (e.g., a 10 minute, er, 600 s, Google search), I conclude ROS does rigorously enforce SI, so units of measure in messages shall be metres/meters (m), seconds (s), newtons (N), radians (rad), Hertz (Hz), etc.

@cdsteinkuehler we're talking about information interchange here. It's still up to the writers of the sending and receiving software to get the conversion to/from SI right. Numerical issues will always be with us as long as non-SI units of measure continue to be useful to end users.
