### ISSUE TITLE
Setup of online tutorial material

### ISSUE THREAD

**Issue by luminize** [machinekit/machinekit#189]
There is some basic online info needed on "how to get started" and "how does it work" when starting with LinuxCNC. I propose to fill this void bit by bit in the form of basic instructions and explanations.
Platform, infrastructure and workflow to be decided
Bas

**Comment by strahlex** [comment]
This issue should be moved to either the machinekit.io repository or the documentation repository. Can I close it here?

**Comment by luminize** [comment]
From my point of view: Sure.
Then open an issue at the other repo.
