### ISSUE TITLE
out of memory/large files results in stopped LinuxCNC

### ISSUE THREAD

**Issue by luminize** [machinekit/machinekit#193]
In these two thread is some discussion about LinuxCNC stopping unexpectedly, having the hot-end still hot. The exiting LinuxCNC without switching off this, zeroing the PWM or having a watchdog is another think. This bug is about preventing the out of memory occurring. I volunteered to code this, but I need some guidance in finding the beginning of the path of crumbled :)

https://groups.google.com/forum/#!topic/machinekit/rkCVRKg2-GQ
https://groups.google.com/forum/#!topic/machinekit/A3UvHqbQvN4

**Comment by robEllenberg** [comment]
Hi All,

I'm not sure if this effort is still going on, but I had a thought about a "quick fix" for the in-memory problem. If the linked list storing NML commands is mostly sequentially accessed (i.e. pulling messages off the end to send to motion / IO), then maybe we could use an existing STL-like container designed to do disk swapping automatically? I found this with some searching:

http://stxxl.sourceforge.net/

It probably wouldn't help with the Axis/gremlin memory consumption issue, but it could be useful for the  internals.

**Comment by mhaberler** [comment]
I'm on the case (#106) but got drawn aside by the vtable stuff 

(to be frank that is a lot more interesting..)

**Comment by mhaberler** [comment]
Jean-Paul just made a great suggestion which would be a stopgap to the issue without requiring the full rewrite of the control structure: limit readahead based on interplist size

fact is - the infinite readahead done by task/interp does not add to path quality if the tp queue is stuffed anyway, and I think that is some 1200 entries or so, so it would be fine to not call the interpreter from task if the interplist goes above a (configurable) high water mark

the way it could work is:
- the InterpList class gets a length() member which observes on how many elements are in the list (increment on append, decrement on dequeue)
- the task logic deciding to read ahead or not inspects the interplist length and compares it to a high water mark (taken from the ini file and say defaulted at a few thousand)

the result should be that the interplist size remains bounded regardless of input file size

I guess this is a fairly small change, and should fix the issue for embedded systems (hopefully for good)

**Comment by luminize** [comment]
That sound very logical.
InterpList becoming a buffer :)

**Comment by mhaberler** [comment]
well I'm puzzled - exactly this is already in place, see https://github.com/machinekit/machinekit/blob/master/src/emc/task/emctaskmain.cc#L559-L560, also the InterpList class already has a len() field - so everything seems to be in place

It seems to me we need a bit more thorough investigation of the source of the problem - if this size-limiting does in fact work, the cause of the out-of-memory error must be different

**Comment by mhaberler** [comment]
I would appreciate if somebody having this kind of error could try this trap: https://github.com/mhaberler/machinekit/tree/limit-readahead-by-interplist-size

if task fails with out-of-memory as before, we need to look elsewhere
if it dumps core on the assert, please report the output of:

gdb ../bin/milltask core 
print interp_list.len()
backtrace

**Comment by mhaberler** [comment]
it might make sense to run milltask under valgrind to find the source of leaks

to do so:
- install valgrind
- in the ini, specify  TASK = valgrind --leak-check=yes     milltask
- edit bin/axis and increase the axis timeout (valgrind slows things down very much):

@@ -3049,11 +3049,11 @@ statwait=.01
 while s.axes == 0:
     print "waiting for s.axes"
     time.sleep(statwait)
     statfail+=1
     statwait *= 2
-    if statfail > 8:
+    if statfail > 20:
         raise SystemExit, (
             "A configuration error is preventing Machinekit from starting.\n"
             "More information may be available when running from a terminal.")
     s.poll()
 
- run linuxcnc ../configs/sim/axis/axis_mm.ini  >/tmp/out 2>&1
- torture it with a huge ngc file so the OOM error happens
- post the /tmp/out file

**Comment by mhaberler** [comment]
well, I guess I need an NGC file and a non-Axis config referred to which reproducably causes this error.
anybody has one around?

probably it would help if one just attached gdb to milltask and produce a backtrace like so:

- start your config
- find out pid of milltask
- run 'gdb -p <pid>'
- type 'continue'
- load the ngc file causes the OOM error
- milltask should drop into gdb
- type 'backtrace' and post results

**Comment by luminize** [comment]
I might have one.
Will have to look it up.
Will send it to you by mail

**Comment by evandene** [comment]
Problem Out Of Memory when loading large G code files solved for my Delta Printer with BBB plus BeBoPr++ plus pololu DRV8825 drivers.
Already mentioned by quite a few others here; using the UI "tkemc" (DISPLAY = tkemc) instead of "axis" (DISPLAY = axis) in your lineardelta.ini file (or ÿourmachine.ini file) really does the job. But ... make sure before starting Machinekit, reboot the BBB. I'm not sure but rebooting seems to me that all what was left from the previous config gets cleaned out and you get a fresh start. Also make sure you have zeroed the "A" axis (Extruder) each time you print a new part with "G92 A0" in the header of your G code file or just as an instruction in the MIDI command line.
Homing all three axis one by one feels a little clumsy but you get used to it. Make sure after the homing procedure the display shows you the specific home locations. 
Good luck and run files as big as 30 Mb or bigger without a problem.
