### ISSUE TITLE
Installing (development) Machinekit from pristine Debian image

### ISSUE THREAD

**Issue by luminize** [machinekit/machinekit#229]
Following this thread https://groups.google.com/forum/#!topic/machinekit/98o_d2BMqL0 below the tl;dr version of what some scripts should have as a result when installing Machinekit from a clean debian (VM or not) install.

This is really about "getting machinekit working from ground up”. When setting this up from a pristine system there could be 2 main choices:
-. since one needs to build machinekit one needs to have the developer dependancies anyway.
1. if developing, does one want Alexander his remote ui development tools and dependancies also? Using one of Alexander his GUI possibilities might mean you also have to build this.
2. does one need a RT system?

so there could be 3 scripts/automations IMO
-developer installation of machinekit, repo, workable development platform without RT (I could work on that now)
-Alexanders work on the remote UI’s (QT and other dependencies later)
-installing a preferred RT kernel on the standard pristine image (later, if possible at all)

then one could on the debian distro:
[1] develop machinekit without hardware on a VM or real machine.
[2] develop alex his remote UI work on a VM or real machine.
[3] both of the 2 above together
[4] install machinekit (needed for [1] or [2] or [3]) + rt kernel for this debian distro with appropriate hardware (i.e. (mini itx) PC with( i.e. mesa 6i25 PCIe) IO card).

**Comment by jpmoniz** [comment]
As of this weekend. I was able to follow the instructions and build from a clean VM.  Enabling 3D Acceleration in Virtual Box causes all kinds of OpenGL errors.  Once I disabled it, all Sim configs were working.

**Comment by luminize** [comment]
closing this one, since #765 will be better maintainable and frankly a lot easier.
