### ISSUE TITLE
RTOS documentation

### ISSUE THREAD

**Issue by zultron** [machinekit/machinekit#23]
Almost no documentation about RTOS and the Universal Build has been written.

**Comment by luminize** [comment]
https://github.com/machinekit/machinekit-docs/blob/master/src/code/Debugging-RT-components.asciidoc
https://github.com/machinekit/machinekit-docs/blob/master/src/common/UnifiedBuild.asciidoc

both have not you @zultron and @mhaberler as original author. I think something went wrong with me botching the merges.

is this the documentation you envisioned?

**Comment by luminize** [comment]
I close this issue since it's in the machinekit-docs. Please re-open if needed.
