### ISSUE TITLE
firmware path handling : needs work

### ISSUE THREAD

**Issue by mhaberler** [machinekit/machinekit#24]
several places use firmware path; at least the hm2 driver and hal_pru_generic.c

the path should be /lib/firmware/{hm2,pru}/pathname, but ideally overridable by an
environment variable FIRMWARE

NB: it should be avoided to link in get_rtapi_config() into RT components, since this
injects the c++ runtime environment into RT

**Comment by ArcEye** [comment]
Seems to have been solved long time ago, even if just by hard coded path.
