### ISSUE TITLE
Possible safety issue: temperature-reading lockup

### ISSUE THREAD

**Issue by brandonheller** [machinekit/machinekit#242]
When using a CRAMPS board with a mostly-stock config:
https://github.com/brandonheller/machinekit/blob/delta/configs/ARM/BeagleBone/CRAMPS/CRAMPS.lineardelta.ini

... I experienced some intermittent stepper motor power cutouts, which I eventually tracked down to flaky screw terminal connections.  At one point LCNC got into a state where it showed a temp of ~189C that no longer updated.  Here the PID loop set the extruder to 100%, so the extruder just kept getting hotter and hotter, to where I noticed a foul smell and immediately unplugged the heater wires.  Restarting LCNC didn't fix the stuck reading and there was nothing weird in the kernel or lcnc logs.  

To clear this, I had to restart the whole board, and then it came back to normal.  As you might guess, I no longer trust the setup to run unattended, especially overnight.  Some questions:
- If this happens, where can I look to check temp values and see if temp updates are failing and getting ignored or if the problem is in HW?
- if this happens, how should the software detect this and react?  You could put safeties on both the PID loop AND the sensor.  E.g., if the last 100 sensor values are exactly the same, assume lockout and cut off.  Or, if after 2 minutes of 100% heat, the reported temp has not raised by a degree, lockout and e-stop.

**Comment by strahlex** [comment]
That is a general problem with temperature readigs. We should implement some kind of logic that checks temperature values for validity.

**Comment by alessandrotorre** [comment]
I have the same problem. Tell us something when it will be fixed, please.

**Comment by strahlex** [comment]
You can do limit checking for a start https://github.com/thecooltool/Uni-print-3D/blob/testing/UNIPRINT-3D.hal#L677
I also implemented this component to check the temperature changes for validity: https://github.com/thecooltool/Uni-print-3D/blob/testing/thermistor_check.comp
It is not the best solution and would much appreciate if someone has better idea.
