### ISSUE TITLE
cnc/axis does not start on rtai-4.0

### ISSUE THREAD

**Issue by mbuesch** [machinekit/machinekit#270]
axis does not start on rtai-4.0 with linux-3.8.13.
It shows the startup screen and semi-freezes. The system is still somewhat usable, but some actions like running htop deadlock (running ps works, though)

Here's a photo:
http://bues.ch/misc/machinekit_start.jpg
This is as far as it goes.

**Comment by zultron** [comment]
RTAI threads are deprecated.  Closing ticket.
