### ISSUE TITLE
Remote session launcher

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#273]
Since Machinekit is not bound anymore to local systems a remote session launcher would make sense. Connecting to a machine over SSH is secure and reliable, but provides not a good user experience for users.

**Comment by strahlex** [comment]
I have started working on this topic last week. During implementation I added a few improvement s to the Python modules: https://github.com/machinekit/machinekit/pull/579

**Comment by strahlex** [comment]
This PR introduces mklauncher which will act as remote configuration launcher: https://github.com/machinekit/machinekit/issues/273
