### ISSUE TITLE
Unused signals cause linuxcnc crash

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#278]
When adding a signal in a HAL configuration and not using it (leftover from a previous config) it crashes linuxcnc on startup:

usrmotintf: ERROR: rtapi init failed
emcMotionInit: ini_hal_init fail
/usr/bin/milltask (pid 5937) died on signal 11, backtrace stored in /tmp/backtrace.5937
/usr/bin/milltask exiting
waiting for s.axes

Not sure why it crashes but there should be at least a warning that there is a unused signal if it leads to unexpected behavior.

**Comment by ArcEye** [comment]
Looks like fix worked
