### ISSUE TITLE
looking forward: linuxcnc docs vs machinekit docs

### ISSUE THREAD

**Issue by RunningLight** [machinekit/machinekit#292]
As of this date, the docs in the machinekit repo are still basically linuxcnc docs.

The Readme in the machinekit directory is very misleading (and it is the first thing anyone coming to https://github.com/machinekit/machiinekit sees). There is no machinekit/INSTALL file (cf. Issue 224). The machinekit/docs/README is ... well...you get the point.

I'd like to take a whack at this but I need to know first, has there been any policy developed for how we weave machinekit-specific information into the existing linuxcnc documentation? I can imagine circumstances where a lcnc file simply should be superseded by a machinekit-created file (as in the machinekit/README instance) and others where mk likely will require changes to existing lcnc files as necessary. It seems to me that tracking changes in g.l.o. looks different in these two circumstances. 
Perhaps in the first instance, the lcnc file could be renamed, for instance by appending "-lcnc" so it isn't lost. Is this renaming of a file something git can track?

Regards,
Kent

**Comment by luminize** [comment]
@RunningLight shall we close this one?

**Comment by RunningLight** [comment]
Yes.
