### ISSUE TITLE
lxde desktop menu slightly broken in BBB package

### ISSUE THREAD

**Issue by RunningLight** [machinekit/machinekit#305]
I'm putting the new machinekit/BBB package through its paces.

All the LinuxCNC-related menu items appear in the "Other" submenu in the desktop applications menu.

Reading the relevant configuration files, these items are intended to appear in a "CNC" submenu.

I'm still teaching myself the Tao of LXDE/lxpanel but it appears the file /etc/xdg/menus/applications-merged/cnc.menu isn't being picked up despite the presence of "&lt;DefaultMergeDirs/&gt;" in the file /etc/xdg/menus/lxde-applications.menu. It's the cnc.menu file which declares that applications whose .desktop files contain "Categories=X-CNC;" should appear in a "CNC" submenu. Consequently /usr/share/applications/*.desktop items containing "Categories=X-CNC;" are getting tossed into the catch-all "Other" category by LXDE.

It looks like we have the right files in the right places but I don't know enough about this DE yet to say whether the problem lies in our files or in the LXDE code.

&lt;rant&gt;LXDE may not be bloated but what a bother to require a plethora of files in different places and to require some to be in XML format and some to be in an INI format&lt;rant/&gt;

**Comment by ArcEye** [comment]
We don't produce any BBB packages / images any more
