### ISSUE TITLE
latency-test launcher broken

### ISSUE THREAD

**Issue by RunningLight** [machinekit/machinekit#307]
[on my newly installed machinekit/BBB]

I'm mindful of the dislike some of us have for the latency-test. Nevertheless, it is one of the CNC Submenu items and it is the only one which is seemingly unresponsive.

Looking at its launcher, /usr/share/applications/linuxcnc-latency.desktop, I find 
"Exec=/usr/local/linuxcnc/latency-test"

Well, /usr/local/linuxcnc/latency-test doesn't exist. /usr/bin/latency-test does.

Running the latter from the command line yields:

  debian@beaglebone:~$ /usr/bin/latency-test
  msgd:0 running
  rtapi:0 running
  halcmd: no service UUID (-R <uuid> or MACHINEKIT_INI [GLOBAL]MKUUID) present
  halcmd: no service UUID (-R <uuid> or MACHINEKIT_INI [GLOBAL]MKUUID) present 
  halcmd: no service UUID (-R <uuid> or MACHINEKIT_INI [GLOBAL]MKUUID) present

so at least two things need to be fixed: the launcher "Exec=" line needs to point in the right place and the latency-test script needs to set up properly.

**Comment by ArcEye** [comment]
latency-test works fine AFAICT
