### ISSUE TITLE
libgnomeprintui-2.2 not being installed

### ISSUE THREAD

**Issue by RunningLight** [machinekit/machinekit#345]
1) I built from source following the instructions on machinekit.io.

2) Buried in the output from ./src/configure, I see the line
`checking for libgnomeprintui-2.2... no -- printing from classicladder will not be possible`

This occurs whether I use the `mk-builddeps` approach or the `apt-installbuilddeps` approach to pull in needed packages.

Was `libgnomeprintui2.2-dev` omitted from the appropriate depends in our packages deliberately or accidentally?

**Comment by ArcEye** [comment]
Looks finished
