### ISSUE TITLE
Please do not direct machinekit users to #linuxcnc-devel

### ISSUE THREAD

**Issue by jepler** [machinekit/machinekit#360]
At http://blog.machinekit.io/p/support.html your website suggests that the IRC channel #linuxcnc-devel is a suitable place to ask for help with machinekit.

Please remove this suggestion, as we are unable to provide advice about the development of machinekit.

**Comment by nallar** [comment]
It's currently pointing to #machinekit-devel on freenode, but that's an empty unregistered channel.

Is there a new IRC or do you guys not use IRC for communication currently?

**Comment by mhaberler** [comment]
no IRC used around here

some people use https://gitter.im/machinekit/machinekit

**Comment by ArcEye** [comment]
> It's currently pointing to #machinekit-devel on freenode, but that's an empty unregistered channel.

Please specify what `It` is

There are 3 links on the Support page that this issue concerns, 2 for the Machinekit forum and I for BeagleBone forum.
A search for `freenode` on that page plus comments reveals nothing.

I did however find reference to it in the Contributing page in the main documents and have purged that and multiple other irrelevant legacy references

**Comment by nallar** [comment]
> Please specify what It is
It was the contributing page. I should've been more clear (and opened an issue in the docs repo, not replied to an old one here?), sorry.

**Comment by ArcEye** [comment]
OK, it is sorted now, just awaiting merge.

If you find any more howlers (there are some :stuck_out_tongue_closed_eyes: ), click on the `Edit this page` link.
Fix what you can and draw attention to anything else that needs fixing, but you might not have the info to do so.
