### ISSUE TITLE
configure and make disagree on run-in-place

### ISSUE THREAD

**Issue by RunningLight** [machinekit/machinekit#374]
I built machinekit from source as described in "Build from source" on machinekit.io

I tried to install what I just built but got an error message

``````
$ sudo make install

make: Entering directory `/home/machinekit/machinekit/src'
Makefile:743: *** You configured run-in-place, but are trying to install.
For an installable version, run configure without --enable-run-in-place
and rebuild.  Stop.```
``````

Fair enough. The trouble is, `configure` has no such option `--enable-run-in-place`.

The only mention of `run-in-place` in the output from `configure --help` is the following tidbit

```
Installation directories:
  --prefix=PREFIX         install architecture-independent files in PREFIX
                          [run-in-place]
```

`make` and `configure` don't seem to be on the same page.

**Comment by ArcEye** [comment]
Historical, RIPs build fine with no args at all to configure.
