### ISSUE TITLE
motion: can we kill free and teleop modes, yielding a modeless planner?

### ISSUE THREAD

**Issue by mhaberler** [machinekit/machinekit#396]
I am considering how to remove teleop mode from motion, and possibly free mode; the insane mode switching with all its abortive behavior is a major stumbling block driving motion from more than input source, for instance a more sane jogging architecture but also other applications

for the below it's instructive to read https://github.com/araisrobo/linuxcnc/blob/master/src/emc/motion/teleop-notes

one question I have is on forward kinematics, see https://github.com/araisrobo/linuxcnc/blob/master/src/emc/motion/teleop-notes#L61

First, note also that ALL kinematics currently in the code base yield KINEMATICS_BOTH (i.e. both forward and reverse kins available), which in effect makes teleop and coord mode identical

(1) is it actually conceivable that for ANY machine, you can NOT come up with an unambiguous forward kins? I have a hard time imagining any such scenario - isnt it that given joint positions, one can always compute the cartesian position of the end effector? (I would rather want to)

if the answer to this question is 'no', then teleop mode is a red herring and can be safely dropped (wouldnt be the first fish of this kind, size and age on the angle)

while we are on the subject of removing modes, a second question - on removing free mode; the only use for free mode I see is for homing

Right now the only type of move one can feed the _coord_ mode planner is a cartesian pose, i.e. kins applied, all axes specified, and in homed state

Now assume what is currently coord mode had a new command which specified a move endpoint in _joint_ positions (i.e. which joint(s) affected and how much): this would in effect be a joint move (one or several joints), BUT using the coord mode planner. IOW: no more need for the 'free mode planner', and 'free mode'.

To home with such a modeless planner, one would have to allow such joint moves if unhomed or homed, but not allow axes (coord) moves if unhomed (it would also trivially enable jogging a gantry kins: just specify both joint endpoints)

(2) what am I overlooking? (or is this whale #2 on the angle ;-?)

**Comment by mhaberler** [comment]
I think these are helpful notes: https://github.com/machinekit/machinekit/blob/master/src/emc/motion/teleop-notes

I cannot discern a difference between teleop and coord mode except for the conditions entering the mode, and the source & format of movement commands.

Do we really need teleop? I think it's just a roundabout way of saying "I'm listening to the UI/wheel rather than the interpreter", which has nothing to do with modes but rather input sources.

**Comment by mhaberler** [comment]
@robEllenberg - re your diagram - do you consider the following approach possible:

There's a single locus where goals enter motion
goal commands are tagged as to whether they refer to axis or joints, and which ones
there is always a second kinematics available (identity)
a coord move selects the machine kins, and carries axis movement(s)
a joint move selects the identity kins, and carries joint move(s)

IOW: everything goes through the coord mode planner; just which joints/axes are driven, and which kins is used is determined by a command attribute, not "motion mode"

under such a setup, can we drop the separate planners?

**Comment by mhaberler** [comment]
fyi - the 'loadable tp' branch and underlying vtable support has been merged

**Comment by jpmoniz** [comment]
Firstly please correct me at any point when I am wrong.

Few thoughts on teleop after doing some investigating on why incremental jogging in telleop is not allowed.

Why can't tellop moves be ran through the current tp?  As I under stand in tellop moves are velocity vectors that bypass the Cartesian planner.

Looking at jogs in free mode we just give an endpoint past the joints limits, and then allow it to move until we say stop. What if the same approach was taken with teleop moves but using the coord planner?  Pass the planner a target for the Cartesian axis requested to jog in, past its limit, and let it move until we say stop.  This should be no different the executing an MDI command and then pressing stop halfway through execution.  What am I missing? Would this not help kill the need for teleop, leaving two modes coordinated and free?

**Comment by mhaberler** [comment]
I did not find a good answer why these separate "axis planners" exist either
I think the primary stumbling block is the abortive mode switching (entering/leaving coord mode flushes the motion queue)

**Comment by jpmoniz** [comment]
@mhaberler  @robEllenberg 
Ok so that was my second thought that I held back.  What if you had a que for each mode that may exist. Dependent on the mode is what motion listened to.  I'm thinking for jog while paused and other typical situations if there were dedicated que by mode then jogging while paused or reversing the motion que would be attainable would it not?  Thinking this may be a good use of ring buffers here.
Sorry i'm just trying to understand the issues while learning the innards.

If task is the master, telling the interp what to do, and telling motion what to listen to, does my logic hold up?

**Comment by mhaberler** [comment]
yes, I think multiple queues and switching them could work that way ('jog while pause' kind of does this although there is no upper-level api to the secondary queue, it's just fed by vectors derived from pin values)

that would pave the way towards the "MDI while paused" - when paused, connect a different interp and a different queue, MDI around, then switch back at some safe point (when the new queue is empty again and the machine returned to the position where the switch happened)

I'm not sure the "multiple queue" idea should be tied into mode switching though, I see that rather a different concept from mode switching; my hope was life would be easier with a modeless planner and motion commands which carry the "mode"  on a per-command basis, not a global state switch (which kins to use, and if axes or joints are to move; in the case of joints - which ones)

**Comment by jpmoniz** [comment]
@mhaberler 
In a way I think were thinking the same thing.  The only obstacle I was thinking of was the situation where you have the "Interp list" full of commands from "automatic program execution"  what do you do when you want to pause and switch to jogging?  My thought was to keep those commands in the list and just switch to a different list to get direction from. When done return to the list that you want to listen to and continue. 

Dont get me wrong I like the idea of having a position command with status flags to indicate who should listen and why.  I just dont know the code enough to suggest a workable solution.

JP
