### ISSUE TITLE
cython v21 (jessie) does not work with MK

### ISSUE THREAD

**Issue by ArcEye** [machinekit/machinekit#413]
Since commit 03a9ca125a200ba763e4b32fd1c9b837c65d0f46, forcing cython installation, noticed that v19 cython from wheezy-backports works, 
but v21 from jessie fails with errors relating to 
cimport statements being out of scope
(I am paraphrasing because I have cleared the original output, but essentially complaining that the
cimport specified was not in the PWD or immediate dirs)

Unsure if this requires an environment variable set, or it is plain broken

**Comment by mhaberler** [comment]
hard to tell with the exact error message - could you make clean, rebuild and paste the error text? 

@zultron  and me are aware of some issues re cython versioning

I gave it a stab, and failed at the abysmal documentation of the cython change which caused the error to crop up; just couldnt make sense what actuall was wrong

**Comment by ArcEye** [comment]
Knew you would say that, was not able to muck around with the repo until I had done the last PR.

Now removed v19 and installed v21 again
Relevant section of build output

<addr>
config.log
configure:2655: checking if cython is usable
configure:2661: checking for cython
configure:2679: found /usr/bin/cython
configure:2691: result: /usr/bin/cython
configure:2703: checking for Cython version
configure:2706: result: 0.21.1
configure:2753: Cython executable is '/usr/bin/cython'

build errors:
...............
Compiling hal/utils/pci_read.c
Linking pci_read
/usr/bin/cython -o hal/cython/machinekit/hal.c hal/cython/machinekit/hal.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# made usable: Michael Haberler 6/2014

cimport cython
cimport hal_const
cimport ring_const
from .hal cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal.pyx:12:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...

cimport cython
cimport hal_const
cimport ring_const
from .hal cimport *
from .rtapi cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal.pyx:13:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
cimport cython
cimport hal_const
cimport ring_const
from .hal cimport *
from .rtapi cimport *
from .hal_priv cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal.pyx:14:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
# hal_priv.h declarations

from .hal cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal_priv.pxd:3:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
cimport hal_const
cimport ring_const
from .hal cimport *
from .rtapi cimport *
from .hal_priv cimport *
from .hal_rcomp cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal.pyx:15:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
# hal_ring.h definitions

from .hal cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal_rcomp.pxd:3:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
# hal_ring.h definitions

from .hal cimport *
from .hal_priv cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal_rcomp.pxd:4:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
cimport ring_const
from .hal cimport *
from .rtapi cimport *
from .hal_priv cimport *
from .hal_rcomp cimport *
from .hal_ring cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal.pyx:16:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
# hal_ring.h definitions

from .hal cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal_ring.pxd:3:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
# hal_ring.h definitions

from .hal cimport *
from .ring cimport ringbuffer_t
^
------------------------------------------------------------

hal/cython/machinekit/hal_ring.pxd:4:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
# Cython cdefs for ring.h and multiframe.h

from libc.stdint cimport uint64_t, uint8_t, uint32_t, int32_t
from libc.stddef cimport size_t
from .rtapi cimport rtapi_atomic_type
^
------------------------------------------------------------

hal/cython/machinekit/ring.pxd:5:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal cimport *
from .rtapi cimport *
from .hal_priv cimport *
from .hal_rcomp cimport *
from .hal_ring cimport *
from .hal_iter cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal.pyx:17:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...

from .hal_priv cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal_iter.pxd:2:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...

from .hal_priv cimport *
from .hal_ring cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal_iter.pxd:3:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...

from .hal_priv cimport *
from .hal_ring cimport *
from .hal_group cimport hal_group_t, hal_member_t
^
------------------------------------------------------------

hal/cython/machinekit/hal_iter.pxd:4:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_priv cimport hal_shmem_base, hal_data_u, hal_data, hal_sig_t
^
------------------------------------------------------------

hal/cython/machinekit/hal_group.pxd:1:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_priv cimport hal_shmem_base, hal_data_u, hal_data, hal_sig_t
from .rtapi cimport rtapi_atomic_type
^
------------------------------------------------------------

hal/cython/machinekit/hal_group.pxd:2:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_priv cimport MAX_EPSILON, hal_data_u
^
------------------------------------------------------------

hal/cython/machinekit/hal_pin.pyx:1:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_priv cimport MAX_EPSILON, hal_data_u
from .hal_util cimport shmptr, pin_linked, linked_signal
^
------------------------------------------------------------

hal/cython/machinekit/hal_pin.pyx:2:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...

from cpython.int   cimport PyInt_Check
from cpython.float cimport PyFloat_Check
from cpython.bool  cimport bool

from .hal_priv     cimport hal_shmem_base, hal_data_u, hal_pin_t, hal_sig_t, hal_data
^
------------------------------------------------------------

hal/cython/machinekit/hal_util.pxd:7:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from cpython.int   cimport PyInt_Check
from cpython.float cimport PyFloat_Check
from cpython.bool  cimport bool

from .hal_priv     cimport hal_shmem_base, hal_data_u, hal_pin_t, hal_sig_t, hal_data
from .hal_const    cimport HAL_BIT, HAL_FLOAT,HAL_S32,HAL_U32, HAL_TYPE_UNSPECIFIED
^
------------------------------------------------------------

hal/cython/machinekit/hal_util.pxd:8:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from cpython.float cimport PyFloat_Check
from cpython.bool  cimport bool

from .hal_priv     cimport hal_shmem_base, hal_data_u, hal_pin_t, hal_sig_t, hal_data
from .hal_const    cimport HAL_BIT, HAL_FLOAT,HAL_S32,HAL_U32, HAL_TYPE_UNSPECIFIED
from .hal_const    cimport HAL_IN, HAL_OUT, HAL_IO
^
------------------------------------------------------------

hal/cython/machinekit/hal_util.pxd:9:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from cpython.bool  cimport bool

from .hal_priv     cimport hal_shmem_base, hal_data_u, hal_pin_t, hal_sig_t, hal_data
from .hal_const    cimport HAL_BIT, HAL_FLOAT,HAL_S32,HAL_U32, HAL_TYPE_UNSPECIFIED
from .hal_const    cimport HAL_IN, HAL_OUT, HAL_IO
from .rtapi cimport rtapi_mutex_get,rtapi_mutex_give
^
------------------------------------------------------------

hal/cython/machinekit/hal_util.pxd:10:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_priv cimport hal_data_u
^
------------------------------------------------------------

hal/cython/machinekit/hal_signal.pyx:1:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_priv cimport hal_data_u
from .hal_util cimport hal2py, py2hal, shmptr, valid_dir, valid_type
^
------------------------------------------------------------

hal/cython/machinekit/hal_signal.pyx:2:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_util cimport pin_value
^
------------------------------------------------------------

hal/cython/machinekit/hal_component.pyx:1:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
# net - link signal and pins by name
import sys

from .hal_const cimport HAL_BIT, HAL_FLOAT,HAL_S32,HAL_U32, HAL_TYPE_UNSPECIFIED, HAL_IN, HAL_OUT, HAL_IO
^
------------------------------------------------------------

hal/cython/machinekit/hal_net.pyx:4:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from buffer cimport PyBuffer_FillInfo
from cpython.bytes cimport PyBytes_AsString, PyBytes_Size, PyBytes_FromStringAndSize
from cpython.string cimport PyString_FromStringAndSize
from cpython cimport bool

from .ring cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal_ring.pyx:16:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_util cimport shmptr #hal2py, py2hal, shmptr, valid_dir, valid_type
^
------------------------------------------------------------

hal/cython/machinekit/hal_group.pyx:1:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_util cimport shmptr #hal2py, py2hal, shmptr, valid_dir, valid_type
from .hal_priv cimport MAX_EPSILON, hal_data
^
------------------------------------------------------------

hal/cython/machinekit/hal_group.pyx:2:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_util cimport shmptr #hal2py, py2hal, shmptr, valid_dir, valid_type
from .hal_priv cimport MAX_EPSILON, hal_data
from .hal_group cimport *
^
------------------------------------------------------------

hal/cython/machinekit/hal_group.pyx:3:0: relative cimport beyond main package is not allowed

Error compiling Cython file:
------------------------------------------------------------
...
from .hal_util cimport shmptr #hal2py, py2hal, shmptr, valid_dir, valid_type
from .hal_priv cimport MAX_EPSILON, hal_data
from .hal_group cimport *
from .rtapi cimport  RTAPI_BIT_TEST
^
------------------------------------------------------------

hal/cython/machinekit/hal_group.pyx:4:0: relative cimport beyond main package is not allowed
make: *** [hal/cython/machinekit/hal.c] Error 1
make: Leaving directory `/usr/git/machinekit/src'

</addr>

**Comment by mhaberler** [comment]
well that was exactly the error I was referring to, I couldnt make any sense/find docs/find a patch which gives a clue how to handle this

looks like tuning in on the cython devlist and waterboarding some devs is on order

**Comment by mhaberler** [comment]
I've posted a question to https://groups.google.com/forum/#!forum/cython-users

**Comment by mhaberler** [comment]
bad news - I think we're heading for troubles:

on Dec 26, wheezy-backports updated http://http.at.debian.org/debian-backports/pool/main/c/cython/cython_0.19.1+git34-gac3e3a2-1~bpo60+1_i386.deb 

that is bogus - despite the name, this yields cython 0.21.2:

root@nwheezy:/home/mah/machinekit-prepare/src# apt-get install -t wheezy-backports  cythonReading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  cython
0 upgraded, 1 newly installed, 0 to remove and 93 not upgraded.
Need to get 0 B/2,286 kB of archives.
After this operation, 7,877 kB of additional disk space will be used.
Selecting previously unselected package cython.
(Reading database ... 256187 files and directories currently installed.)
Unpacking cython (from .../cython_0.19.1+git34-gac3e3a2-1~bpo70+1_i386.deb) ...
Processing triggers for man-db ...
Setting up cython (0.19.1+git34-gac3e3a2-1~bpo70+1) ...

However: 
root@nwheezy:/home/mah/machinekit-prepare/src# /usr/bin/cython --version
Cython version 0.21.2

thanks to the above, and the fact we just made cython a build requirement, this means mk is currently not buildable from packages!

**Comment by mhaberler** [comment]
currently the only way to get at cython 0.19 is like so:


 apt-get install python-pip
 pip install --upgrade git+git://github.com/cython/cython@0.19.x

**Comment by mhaberler** [comment]
strike out the above regarding debian wheezy-backports cython being broken. It does report 0.19.2 - which is ok. My fault.

**Comment by mhaberler** [comment]
well a minute ago a friendly cython user posted a suggestion: https://groups.google.com/forum/#!topic/cython-users/wWxLMuHc56Q%5B1-25-false%5D

the fix was:   touch hal/cython/machinekit/__init__.py

works fine now with Cython version 0.21.2 - I think we can close the cython saga for good soonish ;)

**Comment by ArcEye** [comment]
Well done, now I know what all those empty __init__.py files are for:)

**Comment by mhaberler** [comment]
at last.. after making a complete fool out of myselves ;)

**Comment by cdsteinkuehler** [comment]
On 1/6/2015 1:40 AM, ArcEye wrote:
> Well done, now I know what all those empty __init__.py files are for:)

I saw a few of those and was confused by them as well.

Perhaps they should contain a comment indicating they are required to
identify the directory as a python module?

-- 
Charles Steinkuehler
charles@steinkuehler.net
