### ISSUE TITLE
Motion velocity and dtg stuck after movement

### ISSUE THREAD

**Issue by strahlex** [machinekit/machinekit#481]
Since some time the velocity and distance to go outputs of the motion components are stuck at a value greater than 0 after some movements. This effects the HAL pins as well as the corresponding NML messages and therefore the user interfaces (velocity and dtg display).

**Comment by strahlex** [comment]
Could be related to the HAL PRU generic components feedback value `velocity-fb` which never goes back to 0 after a move.

**Comment by mhaberler** [comment]
example to reproduce?

**Comment by strahlex** [comment]
Anything. Just run something on the BBB.

**Comment by strahlex** [comment]
Fix is in https://github.com/machinekit/machinekit/pull/528
