### ISSUE TITLE
Did someone really use a filename with an embedded wildcard? Checkout fails on windoze.

### ISSUE THREAD

**Issue by modmaker** [machinekit/machinekit#544]
Trying to clone the repo on windows for a quick glance. But the checkout failed on the file mentioned below. Of course everybody is using Linux, but should we make it impossible to use something else in case of emergencies? ;-)

suspected file: **machinekit/share/fdm/thermistor_tables/vishay_NTCS0603E3104*XT.txt**

-- Bas

**Comment by strahlex** [comment]
Oh, thermistor name copy and paste error.

Bas Laarhoven writes:

> Trying to clone the repo on windows for a quick glance. But the checkout failed on the file mentioned below. Of course everybody is using Linux, but should we make it impossible to use something else in case of emergencies? ;-)
>
> suspected file: **machinekit/share/fdm/thermistor_tables/vishay_NTCS0603E3104*XT.txt**
>
> -- Bas
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/machinekit/machinekit/issues/544

-- 
Alexander Rössler

**Comment by modmaker** [comment]
Real programmers don't cut and paste ;-)
Sorry. How are we going to fix this? Is there some dependency on this file or can it be renamed without consequences?

**Comment by strahlex** [comment]
Can be renamed. But grep the name to make sure no config uses it and if so rename it there as well.
