### ISSUE TITLE
 'how do I debug a RT component with gdb'  document section

### ISSUE THREAD

**Issue by mhaberler** [machinekit/machinekit#55]
a useful section for the html doc would be to 'how do I debug a RT component with gdb' since it's so much easier now

**Comment by luminize** [comment]
I've moved the machinekit-docs to the machinekit organisation and your document is here https://github.com/machinekit/machinekit-docs/blob/master/src/code/Debugging-RT-components.asciidoc seems like something went wrong with merging because I can't see you as the author.
