### ISSUE TITLE
Unsatisfactory RT performance in Xilinx Zynq processors/FPGA GPIO driver

### ISSUE THREAD

**Issue by claudiolorini** [machinekit/machinekit#554]
Current GPIO driver for the Zedboard has a poor RT behavior due to the presence in the code of 
standard linux syscalls, i propose to modify it in order to guarantee proper RT performance using
direct memory address access to the Zynq GPIO peripheral.

**Comment by mhaberler** [comment]
poor.. I am rather sure your RT threads get relaxed and run as posix

you have to options - rough: direct mmap I/O as in hal_bb_gpio
or the "proper xenomai way" - an RTDM driver - unfortunately "proper" translates into "Xenomai only"

if you google Christophe Blaess gpio rtdm you should find some hints

**Comment by claudiolorini** [comment]
Yeah, as long as you don't touch anything it's work...ish, but if you do anything... BANG!.
I've been testing the modifications as in hal_bb_gpio, it seems that a HAL generated PWM 
jitter stays within 20usecs under any load condition, so maybe can be of use also for motion 
with step/dir drivers...
As soon as i've polished the code and HAL examples i'll issue a PR.

**Comment by mhaberler** [comment]
thats pretty good, bb jitter is around 40uS

**Comment by claudiolorini** [comment]
...the zynq has a dual processor and i've done some IRQ balancing and kept the system overhead at minimum, maybe it's due to that. I've also noted that with the simple PWM generation and running 
simple G-Codes the load stays around 30% on both CPUs, that's encouraging...

**Comment by claudiolorini** [comment]
...my memory is fading, i remembered 20usecs but... 
i've checked the xscope in the lab and got it almost right ;-) (zeros doesn't count, does it?).
Make it more like 200usecs...

**Comment by mhaberler** [comment]
hm, what do you get on latency-test or latency-histogram on this kernel? pastebin a nice image ;)

on the bb latency-test is in the 40uS ballpark

**Comment by claudiolorini** [comment]
...here there are, the tails seems a bit high, consistent with the xcope readings.
![machinekit-07apr2015-373](https://cloud.githubusercontent.com/assets/2323190/7018498/866a1d56-dd05-11e4-8a44-46d3c44881ab.png)

![print_000](https://cloud.githubusercontent.com/assets/2323190/7018520/c9847b9a-dd05-11e4-8162-505a021d8da3.png)

**Comment by claudiolorini** [comment]
moving irqs around:
MMC card IRQ to CPU2:
![machinekit-07apr2015-eth2cpu2](https://cloud.githubusercontent.com/assets/2323190/7019131/087e7826-dd0d-11e4-9baf-277d60f7c228.png)

Eth0 IRQ to CPU2:
![machinekit-07apr2015-mmc2cpu2](https://cloud.githubusercontent.com/assets/2323190/7019129/035b1ffc-dd0d-11e4-99b6-9f25b8c923bc.png)

things changes slightly but xcope measures more or less remains the same...

**Comment by claudiolorini** [comment]
Some developments:
kernel 3.14.17 Xenomai patched, some advancements but still far from 40uS jitter!

![xcope](https://cloud.githubusercontent.com/assets/2323190/7111529/0c3fcbaa-e1c1-11e4-803a-7087761c32da.jpg)

![machinekit-13apr2015-228](https://cloud.githubusercontent.com/assets/2323190/7111532/0fffcd08-e1c1-11e4-9763-a1ba2435bddd.png)
