### ISSUE TITLE
[question] LinuxCNC cross-compilation

### ISSUE THREAD

**Issue by pianodrumguitar** [machinekit/machinekit#58]
I am now trying to cross-compile LinuxCNC for an i.mx6 board with oselas toolchain, and every mention of "docs/INSTALL" seems to look like "See figure 1." (http://web.archive.org/web/20010716062633/http://nethistory.dumbentia.com/nut04.html). I have already applied xenomai project to 3.0.43 kernel we use, so the next step would be to run linuxcnc. Rootfs has been built with ptxdist 2012.03.0. So, the question is: is there is a guide for cross-compilation of LinuxCNC for a random Linux distribution without dpkg or apt? Because, before I checked out to unified-build-candidate-3, I've been fighting with all the options of configure script, trying to get through all the errors, and it would make my work much easier if there is a cross-compilation guide somewhere. Any proper cross-compilation example would be fine, too.

**Comment by the-snowwhite** [comment]
Hmmm
This issue could be closed ? --> #477

**Comment by mhaberler** [comment]
I guess it can... we need @kinsamanka for the honors ;)

**Comment by kinsamanka** [comment]
The solution to issue #791 provides a way to easily cross-compile machinekit.
