### ISSUE TITLE
missing build dependency

### ISSUE THREAD

**Issue by mhaberler** [machinekit/machinekit#585]
it seems we have a build dependency missing, see this thread: https://groups.google.com/forum/#!topic/machinekit/pMSccTKovpY

it would point to a missing dep between rtapi_global.h and rtapi_app.cc in the minimum, I have observed similar issues with components as well

**Comment by strahlex** [comment]
Is the issue still present?

**Comment by mhaberler** [comment]
yes, I think so

**Comment by zultron** [comment]
If we could get someone to make a tarball of the built tree at the point this error crops up, I could try to solve it.  Otherwise, I'm hoping we can start spinning out portions of the code base (e.g. UIs; Tcl junk, if possible) into separate repos and then refactor the build system to use `automake` or `cmake`.

**Comment by mhaberler** [comment]
suspicion from working on the HAL library: the RT comps are missing a dep on src/hal/lib/*.h

**Comment by mhaberler** [comment]
well simply no .d dependency files are generated for userland threads RT comps, and at least since Dec 2014 (3f5d79dd3b7e9ffc864be474b377543f8e7117a7 does not either)

**Comment by mhaberler** [comment]
reading src/Makefile and results of a build, I think it is safe to say anything referring to DEPDIR in the Makefile is baloney - that directory is never created and hence not populated with any files.

one can `-include  $(READ_RTDEPS)` , but  if these files do not exist - no error.

**Comment by mhaberler** [comment]
I think I have a workaround: https://github.com/mhaberler/machinekit/commit/074584ddffbc1c062b91797bc9d9f9f350de14dc

opinions or better solutions?

man, do I hope we can put this build system to rest soonish

**Comment by zultron** [comment]
@mhaberler, your patch makes sense to me, short of testing.

**Comment by mhaberler** [comment]
well it certainly does not hurt, so I'll do a PR
