### ISSUE TITLE
'Show HAL configuration' fails due to missing 'logpath'

### ISSUE THREAD

**Issue by modmaker** [machinekit/machinekit#592]
MK was built from source. Axis is working, motors are moving. But when I open the hal configuration window that fails with the following messages:

```
emcTaskInit: using builtin interpreter
Error in startup script: couldn't load file "/home/bas/work/machinekit/tcl/hal.so": /home/bas/work/machinekit/tcl/hal.so: undefined symbol: logpath
    while executing
"load $::linuxcnc::TCL_LIB_DIR/hal.so"
    (procedure "hal" line 2)
    invoked from within
"hal list $node"
    (procedure "listHAL" line 5)
    invoked from within
"listHAL"
    (procedure "refreshHAL" line 12)
    invoked from within
"refreshHAL"
    (file "/home/bas/work/machinekit/tcl/bin/halshow.tcl" line 578)
```

Since 'logpath' is defined in hal/utils/halcmd_main.c, it looks like the that code is not linked to the library. Can someone with a better understanding of the build system shed some light on this?

Thanks,
-- Bas

**Comment by mhaberler** [comment]
yes, that was me. Blush. Fix coming.

**Comment by mhaberler** [comment]
Bas, @ArcEye - I merged a fix (out of C4 process..) - please pull and retry

**Comment by ArcEye** [comment]
What is the chance of 2 people finding the same error at pretty much the same time?!

Have done the pull and it builds, but will have to reboot, had problem with the mutex auto-release not working whilst doing the mods to halcmd and now realtime is jammed:(

Let you know soon

**Comment by ArcEye** [comment]
Yes, that works again

**Comment by modmaker** [comment]
Thanks, pulled changes and building right now.

**Comment by modmaker** [comment]
Fixed!
