### ISSUE TITLE
hal_bb_gpio missing from BBB Xenomai packages

### ISSUE THREAD

**Issue by strahlex** [machinekit/machinekit#607]
the `hal_bb_gpio` HAL component shared object seems to be missing from the current version of the Debian packages.

Looking at the buildbot output I found this error message, not sure it is related:
```
../scripts/check-build-vs-configure-sha: line 11: not: command not found
```

I also noticed that the `configure` step is run without the `--with-platform-beaglebone` argument. However, I tried to build machinekit from source without this option and the missing component was still created.

**Comment by strahlex** [comment]
Looking at the buildbot output I cannot find that the component is linked so this seems to be a problem with build not the packaging itself. Has anything with the build infrastructure changed lately?

http://buildbot.dovetail-automata.com/builders/d7-bb-pkg/builds/750/steps/chroot-build-binary-package/logs/stdio

**Comment by strahlex** [comment]
I think I found the problem with the `--build=arm-linux-gnueabihf` argument configure seems to disable the beaglebone libraries: `checking platform-beaglebone... disabled for this architecture`

**Comment by strahlex** [comment]
The solution to fix this problem is explicitely adding `--with-platform-beaglebone` to the ./configure command. I guess the `--build` and `--host` arguments where added recently to the switch to the docker infrastructure.

**Comment by zultron** [comment]
The Jessie changes include multi-arch changes that revealed weakness in #257.  #608 isn't a very good fix; it really should run those checks in one place and set a variable.  I figure we're going to have to address this more fully later, though, so good enough for now....
