### ISSUE TITLE
machinekit.ini is deleted with make clean

### ISSUE THREAD

**Issue by strahlex** [machinekit/machinekit#621]
In RIP installs make clean seems to delete the machinekit.ini file which is not very intuative...
Luckily `./configure` creates a new one but all settings are lost.

**Comment by zultron** [comment]
That's [my fault][1] from PR #600.  The GNU coding standards say `make clean` should not remove anything generated by `./configure`.  I'll set up a new PR.

[1]: https://github.com/machinekit/machinekit/pull/609/files#diff-f57f2991a6aa25fe45d8036c51bf8b4dR708

**Comment by zultron** [comment]
Buildbot passes.
