### ISSUE TITLE
AM335x eQEP velocity measurements on eQEP0 inaccurate

### ISSUE THREAD

**Issue by machinekoder** [machinekit/machinekit#728]
For the Halanduino project we use two eQEP devices, 0 and 2. For some reason the measurements results on eQEP0 are very inaccurate at low speeds even with the time capture unit enabled. First I suspected the encoder, but after exchanging the two encoders I got the same results with the other encoder and eQEP0. 

I am not sure what the source of the problem may be. However, it should be noted that the eQEP0 device uses one of the "shared" pinmux pins P9.42. @cdsteinkuehler Could it be that the double pinmux in this pin overlays the signal? Unfortunately I have no logic analyzer at hand to eliminate the hardware as problem source.

**Comment by ArcEye** [comment]
@machinekoder @cdsteinkuehler 
is this still relevant?
