### ISSUE TITLE
gcc5 builds likely to be broken

### ISSUE THREAD

**Issue by mhaberler** [machinekit/machinekit#740]
not really about mk but rather about gcc5:

debian is transitioning to gcc5

in the process the ABI changed, which means several libraries will have to be upgraded as well, among them protobuf
moreover, I get the impression gcc5 has code generation issues - some regression tests just loop

gcc5: currently not recommend

**Comment by ArcEye** [comment]
Historical, overtaken by events.
A lot of arm toolchains still use gcc 4.9 , whereas amd64 is on v8.2 in sid !
