### ISSUE TITLE
lincurve component bad math

### ISSUE THREAD

**Issue by presslab-us** [machinekit/machinekit#784]
The lincurve component is acting weird, and it looks like some refactoring created a bug.  The order of operations was changed in a formula which screwed up the interpolation.

Here's the new code
https://github.com/machinekit/machinekit/blob/master/src/hal/i_components/lincurve.icomp#L60
And the old code
https://github.com/jepler/linuxcnc-mirror/blob/master/src/hal/components/lincurve.comp#L61

You can see the added parenthesis are in the wrong spot.

**Comment by luminize** [comment]
do you have a development setup where you can make a PR?

**Comment by presslab-us** [comment]
No, sorry.  I could try to get one set up, but I remember last time I compiled it I struggled with the dependencies a bit.

**Comment by luminize** [comment]
ok, I’ll pick this one up later
Bas

**Comment by ArcEye** [comment]
Looks like an auto-completion of brackets typo.

I have junked Geany because of that and other problems.
Just trying a re-build now

**Comment by ArcEye** [comment]
Fix added to PR at
https://github.com/machinekit/machinekit/pull/783

**Comment by presslab-us** [comment]
Thanks guys!!

**Comment by luminize** [comment]
@presslab-us there's a problem regarding the buildbot and generating the package for the ARM platforms. The ARM packages will not be built, so at this time, unless you're not running from ARM packages you cannot upgrade yet. Sorry :(

**Comment by presslab-us** [comment]
Okay, yes I'm using a BBB.  I'm using the lincurve to correct spindle speed on a cheap spindle controller.  So for now I will just fudge it.  But I am happy to know that it will be fixed eventually.  :)

**Comment by luminize** [comment]
@presslab-us now that there should be packages again, can you update and see if the problem is still around?

**Comment by presslab-us** [comment]
Great!  Yes I will test it soon, should be in the next couple days.

**Comment by presslab-us** [comment]
I have confirmed that this is working properly now.  Thanks guys!

**Comment by luminize** [comment]
@presslab-us Thanks for the feedback!
