### ISSUE TITLE
Setting up Google Hangout meetups and Machinekit Calendar

### ISSUE THREAD

**Issue by luminize** [machinekit/machinekit#789]
These meetups will be open to people interested in the subject of the meetup and are meant to improve communication by discussing topics, share knowledge and insights in a face-to-face situation.

These links will be the links you can use for your all time favourite Machinekit calendar. Only the HTML link you can use for directly viewing in your browser. The other ones you can use to connect to the calendar from for example the "Calendar" app on a Mac:

- [ical link](https://calendar.google.com/calendar/ical/machinekit.io%40gmail.com/public/basic.ics)
- [html link](https://calendar.google.com/calendar/embed?src=machinekit.io%40gmail.com&ctz=Europe/Amsterdam)

Until we have some experience and can fine-tune we'll start like this:
* People who have an idea/proposal/wish for a meetup discuss this on the machinekit list or in an issue (new or existing one) and decide together when that's to take place. The first one (at the time of writing this its schedule is yet unknown) is mentioned here: https://github.com/machinekit/machinekit/issues/788
* When the time has been decided somebody needs to ping me (let's start with me and expand when this proves to work) to add an event in the Machinekit calendar.
* This event will show up in your calendar which you have added from the above links.
* I'll add as only invite the machinekit list, so the invite will show up as a post. Exposing the event.

Logically the ones having the meeting can put links to the event in the places they deem necessary.

All other stuff regarding the setting up of these events, calendar and workflow please comment in this thread.

**Comment by mhaberler** [comment]
could you add the Dec 1 and Dec 8 hangouts to the calendar?

**Comment by luminize** [comment]
I've just set the Calender of the machinekit.io@gmail.com account and updated the links in comment https://github.com/machinekit/machinekit/issues/789#issue-117438841
