### ISSUE TITLE
fatal error: demo.pb.h: No such file or directory

### ISSUE THREAD

**Issue by zhivko** [machinekit/machinekit#828]
Pulled sources from git, went through "building from source" documentation and after that trying to make
~/git/machinekit/src/machinetalk/tutorial/json-ws
with make all, I get:
machinekit@beaglebone:~/git/machinekit/src/machinetalk/tutorial/json-ws$ make all
g++ -std=c++0x -g -fPIC -Wall -I../protobuf -I../../../../include -pthread       -I/usr/include/uuid   -D_REENTRANT   -I/usr/include/uriparser     -c -o webtalk_demoplugin.o webtalk_demoplugin.cc
webtalk_demoplugin.cc:11:21: fatal error: demo.pb.h: No such file or directory
compilation terminated.
make: **\* [webtalk_demoplugin.o] Error 1
machinekit@beaglebone:~/git/machinekit/src/machinetalk/tutorial/json-ws$ locate demo.pb.h
machinekit@beaglebone:~/git/machinekit/src/machinetalk/tutorial/json-ws$ sudo updatedb
machinekit@beaglebone:~/git/machinekit/src/machinetalk/tutorial/json-ws$ locate demo.pb.h
machinekit@beaglebone:~/git/machinekit/src/machinetalk/tutorial/json-ws$ 

Indeed there is no demo.pb.h ob bbb machinekit image.
Can somebody give me some pointers here or direct me to documentation about how to use json-ws - or maybe this infrastructure is not there yet?

**Comment by mhaberler** [comment]
those were examples for the tutorial and not integrated into the build

the demo.proto file lives in the protobuf neighbour directory; run a make there which should build the missing files

some makefile tweaking might be needed
