### ISSUE TITLE
hostmot2-firmware* missing

### ISSUE THREAD

**Issue by luminize** [machinekit/machinekit#850]
during recent install of my mesa 5i20 card I could not install `hostmot2-firmware*` packages.
Manually copying as root the `.BIT` files downloaded from the mesa site to `/lib/firmware/hm2/{yourcard here}/{bitfile}.BIT` solved this.
Looks like these packages were lost during the CI work #791

**Comment by mhaberler** [comment]
note the files from the mesanet site are older than in the hostmot2-firmware* packages

**Comment by luminize** [comment]
also see #866

**Comment by sirop** [comment]
So why not simply fork https://github.com/LinuxCNC/hostmot2-firmware ?

I tried it out locally on wheezy with ghdl and llvm-3.5...

**Comment by machinekoder** [comment]
Good point, this should work.
