### ISSUE TITLE
Compile errors with Libwebsockets >1.6

### ISSUE THREAD

**Issue by halbritt** [machinekit/machinekit#937]
Just attempted to compile master against Libwebsockets v1.7 (default on Ubuntu xenial) and received several errors related to functions that were undeclared.  I presume this is as a result of the fact that functions were renamed from libwebsocket_* to lws_* as of v1.6.

**Comment by mhaberler** [comment]
this is why there are specific libwebsockets packages in the machinekit repo

**Comment by mhaberler** [comment]
a PR fixing this would be welcome!

**Comment by halbritt** [comment]
It is my intention to submit a PR if I can sort out what's required.  Seems pretty obvious, however.

**Comment by mhaberler** [comment]
that'd be great - happy to help

libwebsockets has been moving very fast recently, and the packages in debian are bound to stay behind

one option would be to package libwebsockets 2.0 and add that to our repos, but ideally the code should work with what is in the debian repos and with bleeding edge

**Comment by mhaberler** [comment]
@halbritt in case you're using webtalk, I'd appreciate if you could give it a test 

we currently do not have a regression test for webalk

**Comment by mhaberler** [comment]
fixed AFAICT, closing
