### ISSUE TITLE
Stepconf broken in debian package

### ISSUE THREAD

**Issue by michelrdagenais** [machinekit/machinekit#938]
In the latest debian package, machinekit_0.1.1463374659-1mk.travis.master.git0c69cebf-1wheezy_amd64.deb, and possibly those before, many files are still installed in /usr/share/linuxcnc, while applications such as stepconf are looking for files in /usr/share/machinekit.

To reproduce, install machinekit debian packages on debian wheezy, run stepconf using default values and at the end, when clicking "done", stepconf will complain that /usr/share/machinekit/...../tool.tbl cannot be found (from python line: self.copy(base, "tool.tbl").

**Comment by ArcEye** [comment]
Should be fixed by #940

When merged and new packages generated, please test, report back and close issue if resolved.
