### ISSUE TITLE
Missing menu desktop files such as stepconf

### ISSUE THREAD

**Issue by michelrdagenais** [machinekit/machinekit#939]
In machinekit/debian/extras/usr/share/applications commit https://github.com/machinekit/machinekit/commit/bb4d58c9a0e5533727280b80e945076eea81c09f comes with the comment: Deleted desktop files for documentation since no longer in build; changed debian/rules.in so that non-existence of old desktop links to defunct documentation does not cause a fatal build error in buildbot.

The directory contained earlier several files, many of which were documentation, but there were notably entries for latency-test, pncconf and stepconf. Now, only the entry for linuxcnc/machinekit remains. The entries for the other programs should remain IMHO.

linuxcnc.desktop linuxcnc-integratormanual.desktop linuxcnc-developer.desktop linuxcnc-integratormanual-fr.desktop linuxcnc-gcoderef.desktop linuxcnc-latency.desktop linuxcnc-gcoderef-fr.desktop linuxcnc-pncconf.desktop linuxcnc-gettingstarted.desktop linuxcnc-stepconf.desktop linuxcnc-gettingstarted-fr.desktop linuxcnc-usermanual.desktop linuxcnc-halmanual.desktop linuxcnc-usermanual-fr.desktop linuxcnc-halmanual-fr.desktop

**Comment by ArcEye** [comment]
Should be fixed by #940

When merged and new packages generated, please test, report back and close issue if resolved.
