### ISSUE TITLE
MachineKit on FastBot BBP-1S

### ISSUE THREAD

**Issue by WZ9V** [machinekit/machinekit#946]
The FastBot folks have finally (after much pleading on their support forum) released the hardware schematics and some other info needed to make things work.  I'm way way way out of my element on this so I'm hoping others might chime in because this seems like a nice board for MK in my opinion.

https://github.com/fastbot3d/uboot-for-machineKit
https://github.com/fastbot3d/hardware

**Comment by ArcEye** [comment]
Wishlist, not issue, don't look to be any takers.
