### ISSUE TITLE
link:http://www.machinekit.io/docs/building-from-source/ broken in README.asciidoc

### ISSUE THREAD

**Issue by koppi** [machinekit/machinekit#947]
See: https://github.com/machinekit/machinekit/blame/master/README.asciidoc#L41-L42

**Comment by ArcEye** [comment]
The new site has not been announced as live and when it is, we will be asking people to fix simple typos like this themselves.

All will be revealed soon :smile:

**Comment by ArcEye** [comment]
Apologies, I am looking at the wrong thing, thought this was on the document repo, will fix.
